# railway.toml

# Configuration du service web (Serveur Express)
[[services]]
name = "api_map_app"
type = "node"

# Commande de déploiement
[deploy]
command = "node server.js"

# Configuration de l'environnement
env = { NODE_ENV = "production" }